### ISSUE TITLE
cross-compile from darwin (osX) to linux (ubuntu)

### ISSUE THREAD

**Issue by jbowles** [openvenues/gopostal#6]
Any helps or hints appreciated.

Tried many things so far on my mac osX trying to build to ubuntu: `GOOS=linux GOARCH=amd64 go build`:

```ss
pkg-config --libs --cflags libpostal
-I/usr/local/include -L/usr/local/lib -lpostal
```

```sh 
ls /usr/local/lib | grep libpostal
libpostal.1.dylib
libpostal.a
libpostal.dylib
libpostal.la
```

Common issue seems to be when I run:

`CGO_ENABLED=1 GOOS=linux GOARCH=amd64 go build -o fmaplX main.go` give this:

```# runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
with `CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o fmaplX main.go`
```sh                                       
go build github.com/PartnerFusionInc/cable/fmap/vendor/github.com/openvenues/gopostal/expand: no buildable Go source files in /Users/jbowles/gowork/src/github.com/PartnerFusionInc/cable/fmap/vendor/github.com/openvenues/gopostal/expand
go build github.com/PartnerFusionInc/cable/fmap/vendor/github.com/openvenues/gopostal/parser: no buildable Go source files in /Users/jbowles/gowork/src/github.com/PartnerFusionInc/cable/fmap/vendor/github.com/openvenues/gopostal/parser
```

Here is my clang:
```sh
clang --version                                                                                                                     1 ↵ ‹2.4.1›
Apple LLVM version 8.1.0 (clang-802.0.42)
Target: x86_64-apple-darwin16.7.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

And by go env
```sh
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jbowles/gowork"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.8.3/libexec"
GOTOOLDIR="/usr/local/Cellar/go/1.8.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/0_/f4vhytgs455crcjlzfc9dy8h0000gn/T/go-build099799126=/tmp/go-build -gno-record-gcc-switches -fno-common"
CXX="clang++"
CGO_ENABLED="1"
PKG_CONFIG="pkg-config"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
```

**Comment by albarrentine** [comment]
Sorry, afraid I'm not much of a Go user. However, that doesn't sound like it's an issue that's specific to this repo or libpostal.

This project uses cgo, so may be move involved than pure Go projects. Googling the error it seems like you need to set the env variable `CC` to a C cross-compiler as well. Also unless this has been done separately, the libpostal C library would need to be compiled with the same C cross-compiler.

As a more general point, I understand the value of cross-compilation for embedded devices etc. but if the target is Ubuntu, it might be less effort to compile it in a Docker container. John Longanecker has a repo which might be helpful here: https://github.com/johnlonganecker/libpostal-rest-docker. The REST server for that project is written in Go.

**Comment by jbowles** [comment]
Thank you. Yes, it's really more of a CGO problem than libpostal (and possibly osX with clang ... ugh). I was hoping someone had been down this road before :)

For example, `go get`ing the expand and parser packages will not even build correctly unless `CGO_ENABLED=1` (for example, if one gets the packages with cgo disabled and tries to run the tests).

Dockerizing is the way to go, I was in fact hoping to get a cross-compiled binary working while dockrizing all my pieces.

Thank you for the link and comment. I'll go ahead and close this issue since it's not really libpostal/gopostal issue... and will repost here if I find out more.
